### ISSUE TITLE
Fix incorrect ORCID for SGD curator

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua#665]
Due to a typo in the SGD.yaml, there is an extra "h" in one of our ORCIDs: 
contributor=http://orcid.org/0000h-0001-5472-917X

I've fixed the yaml, but there's that extra "h" in the snapshot noctua: http://snapshot.geneontology.org/products/annotations/noctua_sgd.gpad.gz

There are also some development models affected, going back to 2017-2018. What's the best way to fix this?  Or should this be in the go-site tracker?

**Comment by kltm** [comment]
This seems to work, same procedure as #636 :
```
find . -type f -name "*.ttl" -print0 | xargs -0 sed -i 's/0000-0002-5283-5283/0000-0003-3394-9805/'
```
I'll run it next time on a production restart:

- [ ] make sure that barista has most current users.yaml in memory (hot update should take care of that)
- [ ] make sure that user has logged out and logged back in again
- [ ] update models in place (server down, rebuild, server up)
- [ ] check after fifteen minutes that they have made it out to github

**Comment by kltm** [comment]
@suzialeksander fixed with https://github.com/geneontology/go-site/commit/30658ecee361110ef233fe96cddb25f966c742f9#diff-3465e4d873d81989b7646e772725b084

**Comment by suzialeksander** [comment]
mentioning @vanaukenk because she just asked about this in the context of Noctua testing

**Comment by suzialeksander** [comment]
Just pinging because we still see this in snapshot dated 2021-07-28

SGD	S000000595	located_in	GO:0000144	PMID:31990274	ECO:0000314			20200327	SGD		contributor=https://orcid.org/0000h-0001-5472-917X|noctua-model-id=gomodel:5e72450500000780|model-state=production

**Comment by vanaukenk** [comment]
@kltm 

I'm not sure what we need to do here.  Do we have to manually fix any instances of the incorrect orcid in existing models?

Thx.

**Comment by kltm** [comment]
@suzialeksander Yes, that was a metadata fix above. We'll need to apply an all model fix (possibly at the next downtime) to purge all models that already have this in there.

```
sjcarbon@moiraine:~/local/src/git/noctua-models/models[master]$:) grep "0000h-0001-5472-917X" *.ttl | cut -f 1 -d ':' | sort | uniq -c
     11 5941cdbd00000169.ttl
     35 5941cdbd00000578.ttl
     18 5966411600000233.ttl
     17 5970219a00000008.ttl
     13 5970219a00000373.ttl
     11 5970219a00000900.ttl
     15 5ae3b0f600000931.ttl
      5 5e72450500000780.ttl
      3 5e72450500000785.ttl
```

This would look like what we did for the ORCIDs.

**Comment by kltm** [comment]
As a note, this would essentially look like:
```
sjcarbon@moiraine:~/local/src/git/noctua-models/models[master]$:) find . -name "*.ttl" -exec sed -i "s/0000h-0001-5472-917X/0000-0001-5472-917X/g" {} +
```

**Comment by suzialeksander** [comment]
yes if you can, as far as i am aware it's still an issue

**Comment by kltm** [comment]
Whether this has been fixed can now be checked in production.

**Comment by vanaukenk** [comment]
I've spot checked the ORCIDs in the first four models in [the list](https://github.com/geneontology/noctua/issues/665#issuecomment-889460322) and they all look good.
I'll let @suzialeksander sign off on this, though, before we close the ticket.
Thanks @kltm

**Comment by suzialeksander** [comment]
yep, I spot checked three more and they look good.  thanks all.
